{"uuid": "d56a23f6-4750-4112-9ae0-7da5cc3947ba", "children": ["54eefaf6-609d-4d1c-890d-aafb2e21635e"], "befores": [{"name": "_xunit_setup_method_fixture_TestDossierUpload", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestDossierUpload' object has no attribute 'driver'\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 821, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 715, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_DossierU.py\", line 39, in setup_method\n    self.driver.get_screenshot_as_png(),\n"}, "start": 1742904083294, "stop": 1742904085310}], "start": 1742904083294, "stop": 1742904085392}