{"uuid": "95e74f15-b04c-428b-98fb-238d37e2ec78", "children": ["095fc7f5-3a7a-457b-b661-c3f45b8bb219"], "befores": [{"name": "setup_teardown", "status": "broken", "statusDetails": {"message": "TypeError: TestCaseManagement() takes no arguments\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_CaseMg.py\", line 56, in setup_teardown\n    self.archives_search = TestCaseManagement(driver)\n"}, "attachments": [{"name": "设置/清理失败截图", "source": "40c5c5b4-3d20-4457-92d5-a1e01c8e209d-attachment.png", "type": "image/png"}], "start": 1744881811528, "stop": 1744881811790}], "start": 1744881811528, "stop": 1744881811928}