{"uuid": "327d228d-f2fc-4abe-a621-810aff2f97cd", "children": ["cdeea1d7-97c0-41f9-a8d0-37059e6b9638"], "befores": [{"name": "setup_class_fixture", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestAssistedRead' object has no attribute 'login'\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_assisted_read.py\", line 23, in setup_class_fixture\n    self.login()\n"}, "steps": [{"name": "测试前置：系统登录", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestAssistedRead' object has no attribute 'login'\n", "trace": "  File \"E:\\AutoTest\\FgAI\\test_001\\test_assisted_read.py\", line 23, in setup_class_fixture\n    self.login()\n"}, "attachments": [{"name": "登录失败截图", "source": "367fe777-baa8-4f28-8007-e37cf1e52038-attachment.png", "type": "image/png"}], "start": 1744618761334, "stop": 1744618761481}], "start": 1744618761334, "stop": 1744618761482}], "start": 1744618761334, "stop": 1744618761487}