{"uuid": "d56ad5a3-2a81-4239-816d-d27da9d096fb", "children": ["a9ddeac8-b9f9-4055-b2c3-b87afd131f59"], "befores": [{"name": "setup_teardown", "status": "broken", "statusDetails": {"message": "TypeError: TestCaseManagement() takes no arguments\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_CaseMg.py\", line 56, in setup_teardown\n    self.archives_search = TestCaseManagement(driver)\n"}, "attachments": [{"name": "设置/清理失败截图", "source": "d552dac0-c782-427c-976a-ba97ac831a66-attachment.png", "type": "image/png"}], "start": 1744881811933, "stop": 1744881812076}], "start": 1744881811933, "stop": 1744881812080}