{"uuid": "9f733671-9e3f-432b-aa24-2d25da9cb460", "children": ["d289a8d0-e2f1-424e-94e1-7690c2fc0bc2"], "befores": [{"name": "_xunit_setup_method_fixture_TestDossierUpload", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestDossierUpload' object has no attribute 'driver'\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 821, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 715, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_DossierU.py\", line 39, in setup_method\n    self.driver.get_screenshot_as_png(),\n"}, "start": 1742904085395, "stop": 1742904087400}], "start": 1742904085395, "stop": 1742904087415}