{"uuid": "504be23f-b436-4d41-a537-4b95abc40790", "children": ["93ff9d05-7834-4c8c-a40f-0e196ea7f3aa", "c12f68f0-1397-4c88-8923-a5f6352b7a1e", "0be7e9e1-fd9f-4684-bb2a-1ecc85b75527", "be992a89-751e-4eaa-aeb8-d40b772c2f48"], "befores": [{"name": "_xunit_setup_class_fixture_TestCaseManagement", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 113\nCurrent browser version is 135.0.7049.85 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00438893+48451]\n\t(No symbol) [0x003CB8A1]\n\t(No symbol) [0x002D5058]\n\t(No symbol) [0x002F5D9C]\n\t(No symbol) [0x002F1AA3]\n\t(No symbol) [0x002F0019]\n\t(No symbol) [0x00320798]\n\t(No symbol) [0x0032047C]\n\t(No symbol) [0x0031A0B6]\n\t(No symbol) [0x002F7E08]\n\t(No symbol) [0x002F8F2D]\n\tGetHandleVerifier [0x00698E3A+2540266]\n\tGetHandleVerifier [0x006D8959+2801161]\n\tGetHandleVerifier [0x006D295C+2776588]\n\tGetHandleVerifier [0x004C2280+612144]\n\t(No symbol) [0x003D4F6C]\n\t(No symbol) [0x003D11D8]\n\t(No symbol) [0x003D12BB]\n\t(No symbol) [0x003C4857]\n\tBaseThreadInitThunk [0x758E5D49+25]\n\tRtlInitializeExceptionChain [0x773BCF0B+107]\n\tRtlGetAppContainerNamedObjectPath [0x773BCE91+561]\n\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 787, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 715, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\AutoTest\\FgAI\\test_001\\base_test.py\", line 26, in setup_class\n    cls.driver = webdriver.Chrome(options=chrome_options)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1744600351654, "stop": 1744600355701}], "start": 1744600351654, "stop": 1744600355906}