{"uuid": "0a14add5-8b8a-4a11-9992-533d1a51d0ba", "children": ["70d1248b-e155-4b54-904f-0c494654dbd0"], "befores": [{"name": "setup_class_fixture", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestAssistedRead' object has no attribute 'login'\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_assisted_read.py\", line 23, in setup_class_fixture\n    self.login()\n"}, "steps": [{"name": "测试前置：系统登录", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestAssistedRead' object has no attribute 'login'\n", "trace": "  File \"E:\\AutoTest\\FgAI\\test_001\\test_assisted_read.py\", line 23, in setup_class_fixture\n    self.login()\n"}, "attachments": [{"name": "登录失败截图", "source": "1b6faf8d-64b4-4286-8da0-ed2e09f3016d-attachment.png", "type": "image/png"}], "start": 1744618760953, "stop": 1744618761235}], "start": 1744618760953, "stop": 1744618761235}], "start": 1744618760953, "stop": 1744618761331}