{"uuid": "d3f462e6-5018-442e-bb58-10c6c6201106", "children": ["bc02099d-44d1-48aa-bec9-9ef0f0afd04b"], "befores": [{"name": "_xunit_setup_class_fixture_TestDossierUpload", "status": "broken", "statusDetails": {"message": "TypeError: find_test_files() missing 1 required positional argument: 'self'\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 787, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 715, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_DossierUp.py\", line 35, in setup_class\n    self.find_test_files()\n"}, "start": 1743672669699, "stop": 1743672672208}], "start": 1743672669699, "stop": 1743672672590}