{"uuid": "f381f5b6-d80f-4412-a5da-26f735d793c0", "children": ["88b727db-81a8-4b79-a3c6-8f43c79d7c1e", "9d0b6c75-7be8-4ef3-92c1-33f3f665540b", "1bccdfa9-a1cd-4dd9-a310-b1bcc94f3535", "049d1114-bb1c-42f7-8205-db8aa5638a26"], "befores": [{"name": "setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=134.0.6998.177)\nStacktrace:\n\tGetHandleVerifier [0x00007FF686B2DF85+26693]\n\t(No symbol) [0x00007FF686A8EAD0]\n\t(No symbol) [0x00007FF6869191CA]\n\t(No symbol) [0x00007FF6868F1763]\n\t(No symbol) [0x00007FF68699F5EE]\n\t(No symbol) [0x00007FF6869BF975]\n\t(No symbol) [0x00007FF6869976C3]\n\t(No symbol) [0x00007FF686960490]\n\t(No symbol) [0x00007FF686961743]\n\tGetHandleVerifier [0x00007FF686E8436D+3525677]\n\tGetHandleVerifier [0x00007FF686E97F3B+3606523]\n\tGetHandleVerifier [0x00007FF686E8CEE3+3561379]\n\tGetHandleVerifier [0x00007FF686BF7C0A+853194]\n\t(No symbol) [0x00007FF686A9990F]\n\t(No symbol) [0x00007FF686A95674]\n\t(No symbol) [0x00007FF686A95816]\n\t(No symbol) [0x00007FF686A84D89]\n\tBaseThreadInitThunk [0x00007FF8EA71E8D7+23]\n\tRtlUserThreadStart [0x00007FF8EC15BF6C+44]\n\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_DossierU.py\", line 44, in setup_class\n    self.driver.get_screenshot_as_png(),\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1003, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1013, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742977143502, "stop": 1742977147461}], "start": 1742977143502, "stop": 1742977147780}