INFO     MessageTest:test_read_notes.py:20 初始化阅卷笔记工具类...
INFO     MessageTest:test_read_notes.py:178 开始测试完整业务流程...
ERROR    MessageTest:test_read_notes.py:206 完整业务流程测试失败: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8F3F2C460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1dea13f3447fd263f6904b643537e6c3/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8F3F2CBB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1dea13f3447fd263f6904b643537e6c3/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8F3F2CBE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1dea13f3447fd263f6904b643537e6c3/screenshot
ERROR    MessageTest:test_read_notes.py:44 截图失败: HTTPConnectionPool(host='localhost', port=57650): Max retries exceeded with url: /session/1dea13f3447fd263f6904b643537e6c3/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8F3EC15E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
INFO     MessageTest:base_test.py:40 清理测试类...
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8F4458B50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1dea13f3447fd263f6904b643537e6c3
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8F4458550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1dea13f3447fd263f6904b643537e6c3
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8F44583D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/1dea13f3447fd263f6904b643537e6c3
INFO     MessageTest:base_test.py:44 浏览器已关闭