{"uuid": "a4f5a4dd-7962-4b07-9fe8-7bd3c4bc8d78", "children": ["db196617-f23b-4630-8b9f-81a143d9e7d7"], "befores": [{"name": "_xunit_setup_class_fixture_TestDossierUpload", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF66C14DF85+26693]\n\t(No symbol) [0x00007FF66C0AEAD0]\n\t(No symbol) [0x00007FF66BF38FFC]\n\t(No symbol) [0x00007FF66BF7F69F]\n\t(No symbol) [0x00007FF66BFB77B2]\n\t(No symbol) [0x00007FF66BFB210E]\n\t(No symbol) [0x00007FF66BFB11B9]\n\t(No symbol) [0x00007FF66BF055E5]\n\tGetHandleVerifier [0x00007FF66C4A436D+3525677]\n\tGetHandleVerifier [0x00007FF66C4B7F3B+3606523]\n\tGetHandleVerifier [0x00007FF66C4ACEE3+3561379]\n\tGetHandleVerifier [0x00007FF66C217C0A+853194]\n\t(No symbol) [0x00007FF66C0B990F]\n\t(No symbol) [0x00007FF66BF041FF]\n\tGetHandleVerifier [0x00007FF66C5225D8+4042392]\n\tBaseThreadInitThunk [0x00007FF98108E8D7+23]\n\tRtlUserThreadStart [0x00007FF9825514FC+44]\n\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 787, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 715, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\AutoTest\\FgAI\\test_001\\base_test.py\", line 31, in setup_class\n    cls.driver.get_screenshot_as_png(),\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1003, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1013, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1744622048461, "stop": 1744622051962}], "start": 1744622048461, "stop": 1744622052091}