{"uuid": "89eb2aba-b517-441b-8080-8ff8c984f52e", "children": ["3a1d21c2-584e-4fc4-822a-4cc3ca3d7bf9"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 113\nCurrent browser version is 134.0.6998.118 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00B08893+48451]\n\t(No symbol) [0x00A9B8A1]\n\t(No symbol) [0x009A5058]\n\t(No symbol) [0x009C5D9C]\n\t(No symbol) [0x009C1AA3]\n\t(No symbol) [0x009C0019]\n\t(No symbol) [0x009F0798]\n\t(No symbol) [0x009F047C]\n\t(No symbol) [0x009EA0B6]\n\t(No symbol) [0x009C7E08]\n\t(No symbol) [0x009C8F2D]\n\tGetHandleVerifier [0x00D68E3A+2540266]\n\tGetHandleVerifier [0x00DA8959+2801161]\n\tGetHandleVerifier [0x00DA295C+2776588]\n\tGetHandleVerifier [0x00B92280+612144]\n\t(No symbol) [0x00AA4F6C]\n\t(No symbol) [0x00AA11D8]\n\t(No symbol) [0x00AA12BB]\n\t(No symbol) [0x00A94857]\n\tBaseThreadInitThunk [0x75005D49+25]\n\tRtlInitializeExceptionChain [0x7726CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7726CDC1+561]\n\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\AutoTest\\FgAI\\conftest.py\", line 67, in driver\n    driver = webdriver.Chrome(options=chrome_options)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742951400387, "stop": 1742951422582}], "start": 1742951400387, "stop": 1742951422873}